# Generated by Django 5.2.4 on 2025-08-17 13:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("social", "0002_job_and_dm_updates"),
    ]

    operations = [
        migrations.AddField(
            model_name="autoreplyrule",
            name="active_from",
            field=models.TimeField(blank=True, null=True, verbose_name="開始時間"),
        ),
        migrations.AddField(
            model_name="autoreplyrule",
            name="active_to",
            field=models.TimeField(blank=True, null=True, verbose_name="終了時間"),
        ),
        migrations.AddField(
            model_name="autoreplyrule",
            name="use_regex",
            field=models.BooleanField(default=False, verbose_name="正規表現"),
        ),
    ]
