# Generated by Django 5.2.4 on 2025-08-17 14:39

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("contenttypes", "0002_remove_content_type_name"),
        ("social", "0003_autoreplyrule_active_from_autoreplyrule_active_to_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="autoreplyrule",
            name="content_type",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="contenttypes.contenttype",
            ),
        ),
        migrations.AlterField(
            model_name="autoreplyrule",
            name="object_id",
            field=models.PositiveBigIntegerField(blank=True, null=True),
        ),
    ]
